[package]
name = "ckb-cli-plugin-protocol"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-index = { path = "../ckb-index" }
ckb-types = { version = "0.38.0" }
ckb-jsonrpc-types = { version = "0.38.0" }
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
faster-hex = "0.3"
